apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: django-js
build:
  artifacts:
  - image: johan/skaffold-demo
    context: ./src
deploy:
  kubectl:
    manifests:
    - ./k8sconfig/app-local/k8s*
profiles: 
- name: hot_reload
  activation:
    - command: hot_reload
  build:
    artifacts:
    - image: johan/skaffold-demo
      context: ./src
      sync:
        infer: ["**/*"]
  deploy:
    kubectl:
      manifests:
      - ./k8sconfig/app-local/k8s*
- name: with_pg
  build:
    artifacts:
    - image: johan/skaffold-demo
      context: ./src
  deploy:
    kubectl:
      manifests:
      - ./k8sconfig/pg/k8s*
      - ./k8sconfig/app/k8s*
