apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: django-js
build:
  artifacts:
  - image: johan/skaffold-demo
    context: ./src
deploy:
  kubectl:
    manifests:
    - ./k8sconfig/app-local/k8s*
profiles:
- name: with_pg
  build:
    artifacts:
    - image: johan/skaffold-demo
  deploy:
    kubectl:
      manifests:
      - ./k8sconfig/pg/k8s*
      - ./k8sconfig/app/k8s*
