 apiVersion: networking.k8s.io/v1 # for versions before 1.14 use extensions/v1beta1
 kind: Ingress
 metadata:
   name: django-ingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
 spec:
   rules:
   - host: django.info
     http:
       paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: skaffold-demo
             port: 
               number: 8000